const routes = {
    home:'/',
    following:'/following',
    upload:'/upload',
    search:'/search',
    profile:'/:nickname',
    live:'/live',
    friend:'/friends', 
    message:'/messages', 
    explore:'/explore', 
    login:'/login', 
    loginphone:'/login/phone-or-email/phone', 
    loginemail:'/login/phone-or-email/email',
    resetwithphone:'/login/phone/forget-password',
    resetwithemail:'/login/email/forget-password',
    signup:'/signup', 
    signupphone:'/signup/phone-or-email/phone', 
    signupemail:'/signup/phone-or-email/email', 
    createusername:'/signup/create-username',
    createdateofbirth:'/signup/create-birthdate',
};
export default routes;