const routes = {
    home:'/',
    following:'/following',
    upload:'/upload',
    search:'/search',
    profile:'/:nickname',
    live:'/live',
    friend:'/friends', 
    message:'/messages', 
    explore:'/explore', 
    login:'/login', 
    loginphone:'/login/phone-or-email/phone', 
    loginemail:'/login/phone-or-email/email',
    resetwithphone:'/login/phone/forget-password',
    resetwithemail:'/login/email/forget-password',
    signup:'/signup', 
    signupphone:'/signup/phone-or-email/phone', 
    signupemail:'/signup/phone-or-email/email', 
    createusername:'/signup/create-username',
    createdateofbirth:'/signup/create-birthdate',
};
export const pagesTitle = {
    [routes.root]: "Tiktok | Make Your Day",
    [routes.following]: "Following | Watch videos from creators you follow | Tiktok",
    [routes.live]: "Tiktok LIVE | Tiktok",
    [routes.search]: (search) => `Find '${search}' on Tiktok | Tiktok Search`,
    [routes.profile]: (name, username) => `${name} (@${username}) Tiktok | Watch ${name}'s Newest Tiktok Videos`,
    [routes.upload]: "Upload | Tiktok",
}
export default routes;